# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a8890c048d518eeb69c297f10f11ff17b50ba385427f8c3083309846a2f10c73a85056395a115ae6f7ea3d8012916e71bdbd7db73e8afc54156c3044fedbb87

test:
  secret_key_base: f0798c2a798f34af6e1b9d0c8134b0ccd929c4632ba9dc2ffe34fa3b0b47c1d0f54ba1ff1d0d2ed121b07522de26b5e017ed0e3f6f713bf0ab97cb6c6547f420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
