Allergy.find_or_create_by!(name: "Dairy-Free")
Allergy.find_or_create_by!(name: "Egg-Free")
Allergy.find_or_create_by!(name: "Gluten-Free")
Allergy.find_or_create_by!(name: "Seafood-Free")
Allergy.find_or_create_by!(name: "Sesame-Free")
Allergy.find_or_create_by!(name: "Soy-Free")
Allergy.find_or_create_by!(name: "Sulfite-Free")
Allergy.find_or_create_by!(name: "Tree Nut-Free")
Allergy.find_or_create_by!(name: "Wheat-Free")
